services:
  _defaults:
    autowire: true
    autoconfigure: true

  App\Service\OpenAIEmbeddingService:
    public: true
  App\Service\RecommendationService:
    public: true
  App\Repository\BookRepository:
    public: true
