doctrine:
  dbal:
    url: '%env(resolve:DATABASE_URL)%'
    types:
      vector: App\Doctrine\Type\VectorType
      datetime: Doctrine\DBAL\Types\DateTimeImmutableType
      datetimetz: Doctrine\DBAL\Types\DateTimeTzImmutableType
      date: Doctrine\DBAL\Types\DateImmutableType
      time: Doctrine\DBAL\Types\TimeImmutableType
    mapping_types:
      vector: vector
  orm:
    auto_generate_proxy_classes: true
    naming_strategy: doctrine.orm.naming_strategy.underscore
    result_cache_driver:
      type: pool
      pool: doctrine.result_cache_pool
    query_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    metadata_cache_driver:
      type: pool
      pool: doctrine.system_cache_pool
    mappings:
      App:
        is_bundle: false
        type: attribute
        dir: '%kernel.project_dir%/src/Entity'
        prefix: 'App\Entity'
        alias: App
